feat: add radio generator
ng-primitives/ng-primitives pull request #59
Opened 2024-09-10 19:15 UTC by kedevked

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ng-primitives/ng-primitives/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation changes
- [ ] Other... Please describe:

## What does this PR implement/fix?

Add a generator for a radio component

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2024-09-10 19:16 UTC, kedevked commented
I did base the generated code upon this: https://stackblitz.com/edit/angular-es2sm2-1x3uku?file=src%2Fmain.ts

2024-09-11 17:09 UTC, ashley-hunter commented
Thank you! I had some time to put together an example of how I expect the components to be used in an app. Hopefully this is of some help:

https://stackblitz.com/edit/stackblitz-starters-vjuspo?file=src%2Fmain.ts

2024-09-13 19:51 UTC, ashley-hunter requested changes
Looks good, just had a suggestion for the output components

2024-09-16 20:47 UTC, kedevked commented
The generator generates a radio-item component as well now

2024-09-17 19:34 UTC, ashley-hunter requested changes
Looks good, just one small suggestion

2024-09-17 19:34 UTC, ashley-hunter commented on packages/ng-primitives/schematics/radio/generator.ts
> +:host[data-checked="true"] p {}`;
I think we can remove a few of these rules, we don't know that there would be a `p` tag or an `.indicator-dot` etc.., so we can remove these and keep only the things that are a "given"

```suggestion
:host {}

:host[data-hover="true"] {}

:host[data-focus-visible="true"] {}

:host[data-press="true"] {}

:host[data-checked="true"] {}

[ngpRadioIndicator] {}

:host[data-checked="true"] [ngpRadioIndicator] {}
`;
```

2024-09-24 09:17 UTC, ashley-hunter approved these changes
All good, thank you

2024-09-24 09:18 UTC, merged